apiVersion: ddbctl.operators.jittakal.io/v1alpha1
kind: DeleteTablePartitionDataJob
metadata:
  labels:
    app.kubernetes.io/name: deletetablepartitiondatajob
    app.kubernetes.io/instance: deletetablepartitiondatajob-sample
    app.kubernetes.io/part-of: ddbctl-dtp-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ddbctl-dtp-operator
  name: deletetablepartitiondatajob-sample
spec:
  # TODO(user): Add fields here
