apiVersion: ddbctl.operators.jittakal.io/v1alpha1
kind: DeleteTablePartitionDataJob
metadata:
  labels:
    app.kubernetes.io/name: deletetablepartitiondatajob
    app.kubernetes.io/instance: deletetablepartitiondatajob-orders
    app.kubernetes.io/part-of: ddbctl-dtp-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ddbctl-dtp-operator
  name: deletetablepartitiondatajob-orders
spec:
  tableName: Orders
  partitionValue: TESTTENANTID
  endpointURL: http://aws-dynamodb-local.default.svc.cluster.local:8000
  awsRegion: us-east-1
